// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CatCard: typeof import('./src/components/CatCard.vue')['default']
    VanillaCard: typeof import('./src/components/VanillaCard.vue')['default']
    XmasCard: typeof import('./src/components/XmasCard.vue')['default']
  }
}
