// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FluentEmojiBell: typeof import('~icons/fluent-emoji/bell')['default']
    FluentEmojiRedQuestionMark: typeof import('~icons/fluent-emoji/red-question-mark')['default']
    FluentEmojiRibbon: typeof import('~icons/fluent-emoji/ribbon')['default']
    QuestionCard: typeof import('./components/QuestionCard.vue')['default']
    XmasCard: typeof import('./components/XmasCard.vue')['default']
  }
}
